categoriasMain/urls.py
from django.urls import path
from . import views

app_name='category'#esto es necesario para el ciclo for del template
urlpatterns=[
    path('<int:pk>/', views.categoriasDetail, name='categoriasDetail'),
]

item/urls.py
from django.urls import path
from . import views

app_name='item'
urlpatterns=[
    path('',views.items,name='items'),
    path('<int:pk>/', views.detail, name='detail'),
]

storedjango/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from storedjango import settings
from tienda.views import index, contact, product

'''
path: el contact/ es la url en el navegador, mientras
que se usa el name='contacto' se refiere al modo en el que se
llamara a ella en el archivo html
'''
urlpatterns = [
                  path('', index, name='index'),
                  path('items/', include('item.urls')),
                  path('contact/', contact, name='contacto'),
                  path('product/', product, name='product'),
                  path('admin/', admin.site.urls),
                  path('categorias/',include('categoriasMain.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from tienda import views

urlpatterns = [
    path('', views.index, name='index'),
]

categoriasMain/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    images = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

categoriasMain/views.py
from django.shortcuts import render,get_object_or_404
from item.models import Item,Category

# def categoriasDetail(request,pk):
#     item=get_object_or_404(Item,pk=pk)
#     categorias = Category.objects.all()
#     specificItems=Item.objects.filter(category=item.category,is_sold=False)
#     return render(request, 'categorias/categoriasDetail.html',{
#         'item':item,
#         'categorias':categorias,
#         'specificItems':specificItems,
#         'category': item.category, 
#     })
def categoriasDetail(request, pk):
    category = get_object_or_404(Category, pk=pk)
    items = Item.objects.filter(category=category)
    return render(request, 'categorias/categoriasDetail.html', {
        'category': category, 'items': items
        })

item/views.py
from django.shortcuts import render,get_object_or_404
from django.db.models import Q
from .models import Item,Category
def items(request):
    query=request.GET.get('query','')
    items=Item.objects.filter(is_sold=False)
    category_id=request.GET.get('category',0)
    categories=Category.objects.all()
    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items=items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'item/items.html',{ 
        'items':items,
        'query':query,
        'categories':categories,
        'category_id':int(category_id)
             })
def detail(request, pk):
    item=get_object_or_404(Item,pk=pk)
    related_items=Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html',{
        'item':item,
        'related_items':related_items,
                    })

tienda/views.py
from django.shortcuts import render
from item.models import Item, Category


# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    new_items = Item.objects.filter(is_sold=False).order_by("-created_at")[0:3]

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
        'new_items': new_items,
    })


def contact(request):
    items = Item.objects.filter(is_sold=False)

    return render(request, 'core/contact.html'
                  , {'items': items
                     })


def product(request):
    items = Item.objects.filter(is_sold=False)
    return render(request, 'core/product.html'
                  , {'items': items
                     })

categoriasMain/templates/categorias/categoriasDetail.html
{% extends 'core/base.html' %}

{% block title %}
{{ category.name }}
{% endblock %} 

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center"> {{item.category.name}} </h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in items%}
            <div>
                <a href="{% url 'item:detail' item.id%}">
                    <div>
                        <img src="{{item.images.url}}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Presio: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
        

    </div>
</div> 

{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}
{{item.name}} 
{% endblock %} 

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{item.images.url}}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{item.name}} </h1>

        <p class="text-gray-600"> <strong> Precio:</strong> {{item.price}} soles</p>
        <p class="text-gray-700"> 
            <strong class="text-gray-500">Descripción: </strong><br>
            {{item.description}}
        </p>

    </div>

</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">PRODUCTOS RELACIONADOS:</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items%}
            <div>
                <a href="{% url 'item:detail' item.id%}">
                    <div>
                        <img src="{{item.images.url}}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Precio: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div> 

{% endblock %} 

item/templates/item/items.html
{% extends 'core/base.html' %}
{% block title %} Items {% endblock %}
{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Busca en los productos disponibles...">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Buscar</button>
            </form>
            <hr class="my-6">

            <p class="font-semibold">Categorias</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200 {% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>









        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items%}
                    <div>
                        <a href="{% url 'item:detail' item.id%}">
                            <div>
                                <img src="{{item.images.url}}" class="rounded-t-xl">
                            </div>
        
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Precio: {{ item.price }} soles</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>







        </div>
    </div>












{% endblock %}

tienda/templates/core/base.html
{% load static %}

<!DOCTYPE html> 
<html> 
    <style>

        .float{
            position:fixed;
            width:60px;
            height:60px;
            bottom:40px;
            right:40px;
            background-color:#25d366;
            color:#FFF;
            border-radius:50px;
            text-align:center;
          font-size:30px;
            box-shadow: 2px 2px 3px #999;
          z-index:100;
        }
        
        .my-float{
            margin-top:16px;
        }
        </style>
    <head> 
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        <title> {% block title %}{% endblock %} | HealthChoose</title>
        </head> 
        <body>
            <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
                <a href="/" class="text-xl font-semibold"><img src="{% static 'LogoTotal.png' %}" width="170"> </a>
                <div class="space-x-6"> 
                    <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Buscar</a>
                
                </div>
            </nav>
            <div class="py-6 px-6 ">
                {% block content %}
                {% endblock %}
            </div>
            <footer class="py-6 px-6 flex justify-between bg-gray-800">
                <div class="w-2/3 pr-10">
                    <h3 class="mb-5 font-semibold text-gray-400"> About</h3>
                    <p class="text-lg text-gray-500">
                        Hola! Nuestro negocio esta dedicado a la venta de accesorios
                        .En esta página podrás encontrar todos los productos con los
                        que contamos actualmente, una vez hayas decidido que quieres solo escribenos
                        por WhattsApp y te lo entregaremos de inmediato.
                    </p> 
                </div>
                <div class="w-1/3">
                    <h3 class="mb-5 font-semibold text-gray-400"> Menu</h3>
                    <ul class="space-y-2">
                        <li><a href="{% url 'product' %}" class="text-lg text-teal-500 hover:text-teal-700">Productos</a></li>
                        <li><a href="{% url 'contacto' %}" class="text-lg text-teal-500 hover:text-teal-700">Contactanos</a></li>

                    </ul>
                </div>
            </footer>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
            <a href="https://api.whatsapp.com/send?phone=51976485545&text=Hola%21%20Quisiera%20m%C3%A1s%20informaci%C3%B3n%20sobre%20sus%20productos%20." class="float" target="_blank">
            <i class="fa fa-whatsapp my-float"></i>
            </a>
        </body>
<html> 

tienda/templates/core/contact.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
Contáctanos! 
{% endblock %} 

{% block content %}

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">


<h1>  Links de contacto</h1>
<p class="text-lg text-gray-500">
   Para realizar la compra puedes escribirnos por nuestro 
   WhattsApp haciendo click 
   <a href="https://api.whatsapp.com/send?phone=51976485545" style="color: blue;"> aquí</a> 
   o por nuestra página de   Instagram.
</p> 
</div> 

{% endblock %}

tienda/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
Bienvenido 
{% endblock %} 

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">NUEVOS PRODUCTOS</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in new_items%}
            <div>
                <a href="{% url 'item:detail' item.id%}">
                    <div>
                        <img src="{{item.images.url}}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Precio: {{ item.price }} soles</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div> 
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categorías</h2>
   
    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="{% url 'category:categoriasDetail' category.id %}">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ category.name }}</h2>
                    <p class="text-gray-500">Items: {{ category.items.count }}</p>
                </div>
            </a>
        </div>

        {% endfor %}

    </div> 
</div> 


{% endblock %}

tienda/templates/core/product.html
{% extends 'core/base.html' %}

{% block title %}
    Productos
{% endblock %}

{% block content %}


    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">

        <h2 class="mb-12 text-3xl text-center">Todos nuestros productos</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.images.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Precio: {{ item.price }} soles</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}